### ISSUE TITLE
Quiz Does Not Submit When Signed In

### ISSUE THREAD

**Issue by cjparent** [google-developer-training/basic-android-kotlin-compose-training-juice-tracker#11]
**URL of codelab:**
https://developer.android.com/courses/quizzes/android-basics-compose-unit-8-pathway-1/android-basics-compose-unit-8-pathway-1?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-8-pathway-1%23quiz-%2Fcourses%2Fquizzes%2Fandroid-basics-compose-unit-8-pathway-1%2Fandroid-basics-compose-unit-8-pathway-1

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**
End of Pathway Quiz

**Describe the problem**
I believe the addition of the 8th unit broke the API to add a badge to signed in user's accounts. The quiz submission fails when signed in and passing the quiz. When not signed in, or getting less than 7/10 correct and failing, the quiz submission functions as expected.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

Failing The Quiz
![Quiz_with_fail](https://user-images.githubusercontent.com/81254746/222542970-7d7c8e38-af20-4380-bf1d-c8f19c1a2257.PNG)

Passing But Not Signed In
![badge_not_signed_in](https://user-images.githubusercontent.com/81254746/222542975-3269ab7e-cc3a-4d0e-b7e5-7f745855213b.PNG)

Passing But Signed In
![quiz_with_sign_in](https://user-images.githubusercontent.com/81254746/222542971-93256d12-808a-4147-86a0-15d8122e554d.PNG)

**Comment by osuleymanova** [comment]
Hello @cjparent,

Thanks for reaching out to us and sharing your concern. 
We couldn't replicate the issue: the quiz was passed, the badge was earned and viewed in profile.
![Screenshot 2023-03-09 at 11 24 58 AM](https://user-images.githubusercontent.com/86437155/224133252-c543d889-cca6-4481-8717-106714f99a57.png)

![Screenshot 2023-03-09 at 11 25 21 AM](https://user-images.githubusercontent.com/86437155/224133396-7fb00739-19df-4219-85ef-3bcbf26377dc.png)

We recommend to clear the browsing history and pass the quiz again. If it doesn't help, please feel free to re-open the ticket.
