### ISSUE TITLE
Wrong File Location for bottomSheet/EntryBottomSheet

### ISSUE THREAD

**Issue by cjparent** [google-developer-training/basic-android-kotlin-compose-training-juice-tracker#13]
**URL of codelab:**
https://developer.android.com/codelabs/basic-android-kotlin-compose-view-interop?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-8-pathway-2%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-view-interop#4

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**
Step 5 - View Interoperability in Compose

**Describe the problem**
 The code example for the 9th task in the "Create the rating input" section shows the location as "bottomsheet/AdBanner.kt" as opposed to "bottomsheet/EntryBottomSheet.kt"

![wrong_file_location](https://user-images.githubusercontent.com/81254746/222545975-1eb2daea-2840-4d52-8d16-0372e189096a.PNG)

**Comment by osuleymanova** [comment]
Hello @cjparent,

Thanks for reaching out to us and reporting this typo. It is fixed and republished soon.
