### ISSUE TITLE
Typo in quiz section

### ISSUE THREAD

**Issue by RaczkaKamil** [google-developer-training/basic-android-kotlin-compose-training-juice-tracker#7]
Hello Googlers, hope your day is going well :)

I am not sure where to report this error, so will try here.  I found an typo in quiz section for the unit:

3. Which of the following are parameters of the AndroidView Composable? Select all that apply.
Choose as many answers as you see fit.
- [ ] factory
- [ ] inputLabel
- [ ] **upcate** <----
- [ ] modifier

https://developer.android.com/courses/quizzes/android-basics-compose-unit-8-pathway-2/android-basics-compose-unit-8-pathway-2?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-8-pathway-2%23quiz-%2Fcourses%2Fquizzes%2Fandroid-basics-compose-unit-8-pathway-2%2Fandroid-basics-compose-unit-8-pathway-2

Have a good day!

**Comment by johnshea** [comment]
Hi @RaczkaKamil 

Thank you for letting us know of this issue.

It has been fixed and it is already live in production.

Hope you are enjoying the course!

Regards.
